# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: gittools.gittools.setup-gitversion-task.gitversion/setup@0
  displayName: gitversion/setup
  inputs:
    versionSpec: 5.x

- task: gittools.gittools.execute-gitversion-task.gitversion/execute@0
  displayName: gitversion/execute

- task: bleddynrichards.Assembly-Info-Task.Assembly-Info-NetCore.Assembly-Info-NetCore@2
  displayName: 'Set Assembly Manifest Data'
  inputs:
    InsertAttributes: true
    Authors: HB9GXP
    VersionNumber: '$(GitVersion.MajorMinorPatch)'
    FileVersionNumber: '$(GitVersion.MajorMinorPatch)'
    InformationalVersion: '$(GitVersion.SemVer)'

- task: qetza.replacetokens.replacetokens-task.replacetokens@3
  displayName: 'Inject version in **/*.sh'
  inputs:
    rootDirectory: install
    targetFiles: '*.sh'
    tokenPrefix: '__'
    tokenSuffix: '__'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    workingDir: 'src/SvxlinkManager'
    verbose: true

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)  -p:PublishProfile=FolderProfile'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish main artifact'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish installer artifact'
  inputs:
    PathtoPublish: install
    ArtifactName: installer
  condition: succeededOrFailed()

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'GitHub Connection'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(GitVersion.MajorMinorPatch)'
    tagSource: 'userSpecifiedTag'
    tag: '$(GitVersion.FullSemVer)'
    title: 'SvxlinkManager $(GitVersion.FullSemVer)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'