<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Channels\**" />
    <EmbeddedResource Remove="Channels\**" />
    <None Remove="Channels\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="SvxlinkManagerConfigs\AdvanceChannel\Commands\" />
    <Folder Include="SvxlinkManagerConfigs\Echolinks\Commands\NewFolder\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SvxlinkManager.Domain\SvxlinkManager.Domain.csproj" />
  </ItemGroup>

</Project>
